name       : python-msgpack
version    : 0.4.8
release    : 1
source     :
    - https://pypi.python.org/packages/21/27/8a1d82041c7a2a51fcc73675875a5f9ea06c2663e02fcfeb708be1d081a0/msgpack-python-0.4.8.tar.gz : 1a2b19df0f03519ec7f19f826afb935b202d8979b0856c6fb3dc28955799f886
license    : Apache-2.0
component  : programming.python
summary    : A fast, compact binary serialization format, suitable for similar data to JSON.
description: |
    MessagePack is a fast, compact binary serialization format, suitable for similar data to JSON.
    This package provides CPython bindings for reading and writing MessagePack data.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
