name       : python-msgpack
version    : 1.0.4
release    : 11
source     :
    - https://pypi.org/packages/source/m/msgpack/msgpack-1.0.4.tar.gz : f5d869c18f030202eb412f08b28d2afeea553d6613aee89e200d7aca7ef01f5f
homepage   : https://msgpack.org/
license    : Apache-2.0
component  : programming.python
summary    : A fast, compact binary serialization format, suitable for similar data to JSON
description: |
    MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. This package provides CPython bindings for reading and writing MessagePack data.
builddeps  :
    - cython
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
