name       : python-msgpack
version    : 0.5.6
release    : 5
source     :
    - https://pypi.org/packages/source/m/msgpack/msgpack-0.5.6.tar.gz : 0ee8c8c85aa651be3aa0cd005b5931769eaa658c948ce79428766f1bd46ae2c3
license    : Apache-2.0
component  : programming.python
summary    : A fast, compact binary serialization format, suitable for similar data
    to JSON
description: |
    MessagePack is a fast, compact binary serialization format, suitable for similar data to JSON.
    This package provides CPython bindings for reading and writing MessagePack data.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-pytest
    - python-six
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD py.test3
    popd
