name       : python-msgpack
version    : 1.0.0
release    : 7
source     :
    - https://pypi.org/packages/source/m/msgpack/msgpack-1.0.0.tar.gz : 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0
license    : Apache-2.0
component  : programming.python
summary    : A fast, compact binary serialization format, suitable for similar data to JSON
description: |
    MessagePack is a fast, compact binary serialization format, suitable for similar data to JSON.
    This package provides CPython bindings for reading and writing MessagePack data.
builddeps  :
    - cython
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
